# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recommendations_pb2 as recommendations__pb2


class BookRecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecommendBooks = channel.unary_unary(
                '/BookRecommendationService/RecommendBooks',
                request_serializer=recommendations__pb2.BookRecommendationRequest.SerializeToString,
                response_deserializer=recommendations__pb2.BookRecommendationResponse.FromString,
                )


class BookRecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecommendBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookRecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecommendBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendBooks,
                    request_deserializer=recommendations__pb2.BookRecommendationRequest.FromString,
                    response_serializer=recommendations__pb2.BookRecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookRecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookRecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecommendBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookRecommendationService/RecommendBooks',
            recommendations__pb2.BookRecommendationRequest.SerializeToString,
            recommendations__pb2.BookRecommendationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
